[project]
name = "elias-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.2",
    "gunicorn>=23.0.0",
    "whitenoise>=6.8.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
